#!/usr/bin/env bash

pid=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.type=="con") | select(.focused==true).pid')
ppid=$(pgrep --newest --parent ${pid})
# readlink /proc/${ppid}/cwd || echo $HOME
pp=$(readlink /proc/${ppid}/cwd)
if [ -z "$pp" ]
then
      echo "/home/jack"
else
      echo "$pp"
fi
